### ISSUE TITLE
Aktualisierung der Demo für 3.x

### ISSUE THREAD

**Issue by kein-nickname** [MetaModels/demo-movie-database#1]
Demo nicht mehr für neuere Versionen nutzbar!!!
Vielleicht einfach einen Download - wie bei Isotope - der SQL-DB, incl. Templates und .CTO anbieten? :)

**Comment by Schnubl** [comment]
Schon was neues bezüglich Version für 3.x.x ?
Wäre auch mit den Files ohne Installer glücklich!

**Comment by discordier** [comment]
In dem Moment wo wir die files haben, haben wir auch einen neuen installer. ;)

Im Ernst, ich sitze aktuell an ganz anderen Dingen um MM stable zu bekommen, da ist leider die Demo bei mir auf unterster Prio, aber es gab letztens jemanden in der Community der ein SQL zur Verfygung stellen wollte.

**Comment by cboelter** [comment]
Ich probiere mich aktuell an der aktualisierung der Demo auf Contao 3.2 und MM-TNG

**Comment by cboelter** [comment]
Ich arbeite gerade an dem Update für 3.2 bräuchte da aber im Frontend hilfe, @tim-bec @MacKP jemand Zeit und Lust?

**Comment by tim-bec** [comment]
Morgen gerne, schickst Du Zugangsdaten / Repro mit Dump? Ich bin heute zu fertig hab ne Nachtschicht hinter mir.

**Comment by cboelter** [comment]
Lass uns dazu mal am Freitag (Nachmittag?) mumblen, ich bereite dann mal eine Testinstallation und so vor und trage auch mal alle Bugs die mir aufgefallen sind zusammen.

**Comment by MoniqueHahnefeld** [comment]
Ich habe die Demo mit der Contao 3.4.5 installiert und sie läuft super. Ich habe noch beim CSS nachgeholfen. Soll ich die Contao-Installation mit SQL-File hier verlinken?? Oder hat sich das schon erledigt :)?
Falls jemand braucht hier die Installation:
http://codeowl.org/metamodels-demo-bundle-c3.4.5.zip

**Comment by MacKP** [comment]
Hallo @MoniqueHahnefeld super! Vielen Dank für die Files :+1:

**Comment by MoniqueHahnefeld** [comment]
Gerne :)

**Comment by zonky2** [comment]
@MoniqueHahnefeld der Link ist tot - liegt das Zip wo anders?

**Comment by cliffparnitzky** [comment]
Der Link heißt nun: http://designs2.de/downloads/metamodels-demo-bundle-c3.4.5.zip

**Comment by zonky2** [comment]
mit Contao 3.5.17 und aktuellem MM
http://www.e-spin.de/contao-metamodels.html

**Comment by zonky2** [comment]
Ich habe noch eine überarbeitete Version hoch geladen, in der verschiedene Sachen auf das aktuelle MM getrimmt sind sowie einige "Schönheitsverbesserungen" wie z.B.
- MMs mit Icons im BE
- Tabellenansichten
- Sortierungen, Filterungen, Suchen im BE eingerichtet
- Übersetzungen DE
- MM per Composer

http://www.e-spin.de/contao-metamodels.html

**Comment by zonky2** [comment]
ist fertig - siehe `Handbuch, Webseite, Videos:` bei https://now.metamodel.me/de/aktuelles/details/2017-august-infos
